"""add_user_location_fields

Revision ID: 7b9aa0df48e9
Revises: 2bfd451b4aed
Create Date: 2026-09-25 06:07:57.966167
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b9aa0df48e9'
down_revision: Union[str, None] = '2bfd451b4aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location_accuracy', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('location_visibility', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    op.drop_column('users', 'location_visibility')
    op.drop_column('users', 'last_location_update')
    op.drop_column('users', 'location_accuracy')
    op.drop_column('users', 'last_longitude')
    op.drop_column('users', 'last_latitude')
    # ### end Alembic commands ###
